set number
set autoindent
colo evening
syntax on
set viminfo+='1000,n~/.config/vim/viminfo

command NN set nu!
command CG !groff -ms %:t -k latin-1 -T pdf > groff.pdf
command! W execute 'w !sudo tee % > /dev/null' <bar> edit!

set ignorecase
set smartcase
set hlsearch
set incsearch
set lazyredraw
set showmatch
set mat=2
set nobackup
set nowb
set noswapfile
