set number
set autoindent
set smartindent
set sw=2
set ts=2
set cc=72
set expandtab
colo evening
syntax on
set viminfo+='1000,n~/.config/vim/viminfo

command NN set nu!
command CG !groff -ms %:t -k -T pdf > %:t.pdf
command! W execute 'w !sudo tee % > /dev/null' <bar> edit!

set ignorecase
set smartcase
set hlsearch
set incsearch
set lazyredraw
set showmatch
set mat=2
set nobackup
set nowb
set noswapfile

